# Packages installations

### Install all these packages  : 
* df-squeezer
* scikit-learn
* lightgbm
* xgboost
* catboost[gpu]
* numpy
* matplotlib
* pandas
* pyarrow
* fastparquet
* torch
* ipykernel 
* tqdm

In [ ]:
pip install -r /kaggle/input/datassets/requirements.txt  # assurer vous de changer le chemin d'acces du requirements

Collecting df-squeezer (from -r /kaggle/input/datassets/requirements.txt (line 1))
  Downloading df_squeezer-0.0.12.tar.gz (3.1 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from -r /kaggle/input/datassets/requirements.txt (line 2)) (1.2.2)
Requirement already satisfied: lightgbm in /usr/local/lib/python3.11/dist-packages (from -r /kaggle/input/datassets/requirements.txt (line 3)) (4.6.0)
Requirement already satisfied: xgboost in /usr/local/lib/python3.11/dist-packages (from -r /kaggle/input/datassets/requirements.txt (line 4)) (2.0.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from -r /kaggle/input/datassets/requirements.txt (line 6)) (1.26.4)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from -r /kaggle/input/datassets/requirements.txt (line 7)) (3.7.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from -r /kaggle/input/datassets/requirements.txt (line 8)) (2.2.3)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.11/dist-packages (from -r /kaggle/input/datassets/requirements.txt (line 9)) (19.0.1)
Collecting fastparquet (from -r /kaggle/input/datassets/requirements.txt (line 10))
  Downloading fastparquet-2024.11.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Requirement already satisfied: torch in /usr/local/lib/python3.11/dist-packages (from -r /kaggle/input/datassets/requirements.txt (line 11)) (2.6.0+cu124)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.11/dist-packages (from -r /kaggle/input/datassets/requirements.txt (line 12)) (6.17.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from -r /kaggle/input/datassets/requirements.txt (line 13)) (4.67.1)
Requirement already satisfied: catboost[gpu] in /usr/local/lib/python3.11/dist-packages (from -r /kaggle/input/datassets/requirements.txt (line 5)) (1.2.8)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->-r /kaggle/input/datassets/requirements.txt (line 2)) (1.15.3)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->-r /kaggle/input/datassets/requirements.txt (line 2)) (1.5.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->-r /kaggle/input/datassets/requirements.txt (line 2)) (3.6.0)
WARNING: catboost 1.2.8 does not provide the extra 'gpu'
Requirement already satisfied: graphviz in /usr/local/lib/python3.11/dist-packages (from catboost[gpu]->-r /kaggle/input/datassets/requirements.txt (line 5)) (0.21)
Requirement already satisfied: plotly in /usr/local/lib/python3.11/dist-packages (from catboost[gpu]->-r /kaggle/input/datassets/requirements.txt (line 5)) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from catboost[gpu]->-r /kaggle/input/datassets/requirements.txt (line 5)) (1.17.0)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy->-r /kaggle/input/datassets/requirements.txt (line 6)) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy->-r /kaggle/input/datassets/requirements.txt (line 6)) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy->-r /kaggle/input/datassets/requirements.txt (line 6)) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy->-r /kaggle/input/datassets/requirements.txt (line 6)) (2025.2.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy->-r /kaggle/input/datassets/requirements.txt (line 6)) (2022.2.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy->-r /kaggle/input/datassets/requirements.txt (line 6)) (2.4.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->-r /kaggle/input/datassets/requirements.txt (line 7)) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->-r /kaggle/input/datassets/requirements.txt (line 7)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->-r /kaggle/input/datassets/requirements.txt (line 7)) (4.59.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->-r /kaggle/input/datassets/requirements.txt (line 7)) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->-r /kaggle/input/datassets/requirements.txt (line 7)) (25.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->-r /kaggle/input/datassets/requirements.txt (line 7)) (11.3.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->-r /kaggle/input/datassets/requirements.txt (line 7)) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib->-r /kaggle/input/datassets/requirements.txt (line 7)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->-r /kaggle/input/datassets/requirements.txt (line 8)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->-r /kaggle/input/datassets/requirements.txt (line 8)) (2025.2)
Requirement already satisfied: cramjam>=2.3 in /usr/local/lib/python3.11/dist-packages (from fastparquet->-r /kaggle/input/datassets/requirements.txt (line 10)) (2.10.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from fastparquet->-r /kaggle/input/datassets/requirements.txt (line 10)) (2025.9.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch->-r /kaggle/input/datassets/requirements.txt (line 11)) (3.19.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch->-r /kaggle/input/datassets/requirements.txt (line 11)) (4.15.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch->-r /kaggle/input/datassets/requirements.txt (line 11)) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch->-r /kaggle/input/datassets/requirements.txt (line 11)) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch->-r /kaggle/input/datassets/requirements.txt (line 11))
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch->-r /kaggle/input/datassets/requirements.txt (line 11))
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch->-r /kaggle/input/datassets/requirements.txt (line 11))
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch->-r /kaggle/input/datassets/requirements.txt (line 11))
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch->-r /kaggle/input/datassets/requirements.txt (line 11))
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch->-r /kaggle/input/datassets/requirements.txt (line 11))
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch->-r /kaggle/input/datassets/requirements.txt (line 11))
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch->-r /kaggle/input/datassets/requirements.txt (line 11))
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch->-r /kaggle/input/datassets/requirements.txt (line 11))
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch->-r /kaggle/input/datassets/requirements.txt (line 11)) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch->-r /kaggle/input/datassets/requirements.txt (line 11)) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch->-r /kaggle/input/datassets/requirements.txt (line 11)) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch->-r /kaggle/input/datassets/requirements.txt (line 11))
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch->-r /kaggle/input/datassets/requirements.txt (line 11)) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch->-r /kaggle/input/datassets/requirements.txt (line 11)) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch->-r /kaggle/input/datassets/requirements.txt (line 11)) (1.3.0)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.11/dist-packages (from ipykernel->-r /kaggle/input/datassets/requirements.txt (line 12)) (1.8.15)
Requirement already satisfied: ipython>=7.23.1 in /usr/local/lib/python3.11/dist-packages (from ipykernel->-r /kaggle/input/datassets/requirements.txt (line 12)) (7.34.0)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.11/dist-packages (from ipykernel->-r /kaggle/input/datassets/requirements.txt (line 12)) (8.6.3)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.11/dist-packages (from ipykernel->-r /kaggle/input/datassets/requirements.txt (line 12)) (0.1.7)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.11/dist-packages (from ipykernel->-r /kaggle/input/datassets/requirements.txt (line 12)) (1.6.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from ipykernel->-r /kaggle/input/datassets/requirements.txt (line 12)) (7.1.0)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.11/dist-packages (from ipykernel->-r /kaggle/input/datassets/requirements.txt (line 12)) (26.2.1)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.11/dist-packages (from ipykernel->-r /kaggle/input/datassets/requirements.txt (line 12)) (6.5.2)
Requirement already satisfied: traitlets>=5.1.0 in /usr/local/lib/python3.11/dist-packages (from ipykernel->-r /kaggle/input/datassets/requirements.txt (line 12)) (5.7.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.11/dist-packages (from ipython>=7.23.1->ipykernel->-r /kaggle/input/datassets/requirements.txt (line 12)) (75.2.0)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.11/dist-packages (from ipython>=7.23.1->ipykernel->-r /kaggle/input/datassets/requirements.txt (line 12)) (0.19.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.11/dist-packages (from ipython>=7.23.1->ipykernel->-r /kaggle/input/datassets/requirements.txt (line 12)) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.11/dist-packages (from ipython>=7.23.1->ipykernel->-r /kaggle/input/datassets/requirements.txt (line 12)) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from ipython>=7.23.1->ipykernel->-r /kaggle/input/datassets/requirements.txt (line 12)) (3.0.51)
Requirement already satisfied: pygments in /usr/local/lib/python3.11/dist-packages (from ipython>=7.23.1->ipykernel->-r /kaggle/input/datassets/requirements.txt (line 12)) (2.19.2)
Requirement already satisfied: backcall in /usr/local/lib/python3.11/dist-packages (from ipython>=7.23.1->ipykernel->-r /kaggle/input/datassets/requirements.txt (line 12)) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.11/dist-packages (from ipython>=7.23.1->ipykernel->-r /kaggle/input/datassets/requirements.txt (line 12)) (4.9.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.11/dist-packages (from jupyter-client>=6.1.12->ipykernel->-r /kaggle/input/datassets/requirements.txt (line 12)) (5.8.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch->-r /kaggle/input/datassets/requirements.txt (line 11)) (3.0.2)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy->-r /kaggle/input/datassets/requirements.txt (line 6)) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy->-r /kaggle/input/datassets/requirements.txt (line 6)) (2022.2.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy->-r /kaggle/input/datassets/requirements.txt (line 6)) (1.4.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy->-r /kaggle/input/datassets/requirements.txt (line 6)) (2024.2.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly->catboost[gpu]->-r /kaggle/input/datassets/requirements.txt (line 5)) (8.5.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy->-r /kaggle/input/datassets/requirements.txt (line 6)) (2024.2.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.11/dist-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel->-r /kaggle/input/datassets/requirements.txt (line 12)) (0.8.4)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.11/dist-packages (from jupyter-core!=5.0.*,>=4.12->jupyter-client>=6.1.12->ipykernel->-r /kaggle/input/datassets/requirements.txt (line 12)) (4.4.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.11/dist-packages (from pexpect>4.3->ipython>=7.23.1->ipykernel->-r /kaggle/input/datassets/requirements.txt (line 12)) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.11/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.23.1->ipykernel->-r /kaggle/input/datassets/requirements.txt (line 12)) (0.2.13)
Downloading fastparquet-2024.11.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 25.6 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.8 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 80.8 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 55.9 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 47.2 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.3 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 2.1 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 27.1 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 12.8 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 7.9 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 50.2 MB/s eta 0:00:0000:0100:01m
Building wheels for collected packages: df-squeezer
  Building wheel for df-squeezer (setup.py) ... done
  Created wheel for df-squeezer: filename=df_squeezer-0.0.12-py3-none-any.whl size=3465 sha256=5505ee992b33fa98f435fce579af0bf4e6d5ff6d03dc86fd75381f832404d9a2
  Stored in directory: /root/.cache/pip/wheels/63/ef/7d/95c3a3c2f0210d1385c2a539837efe342ab657dbff8ed76c3f
Successfully built df-squeezer
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, fastparquet, df-squeezer
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:

### 0. Imports and requirements

In [2]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sn
# Input data files are available in the read-only "../input/" director.ai/competitions/aivkchallengey
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

from df_squeezer import df_squeezer
from sklearn.metrics import roc_auc_score, accuracy_score

%load_ext autoreload
%autoreload 2

import gc
import os
import sys
import pandas as pd
import numpy as np
import tqdm
import seaborn as sns


import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.model_selection import train_test_split, StratifiedKFold, KFold
from sklearn.metrics import roc_auc_score
from sklearn.linear_model import LogisticRegression


pd.set_option('display.max_columns', None)
os.environ["CUDA_VISIBLE_DEVICES"] = '0'

sys.path.append('../')

# 1. Reading Data and Memory Reduction

In [3]:

train = pd.read_parquet("/kaggle/input/datassets/train.parquet") # veillez adpter le chemin d'acces au votre 
test = pd.read_parquet("/kaggle/input/datassets/test.parquet") # veillez adpter le chemin d'acces au votre
train=df_squeezer(train, edit=True, report=False)
test=df_squeezer(test, edit=True, report=False)

# 2.  Data Preporcessing

In [4]:
train.head()

,id,rn,pre_since_opened,pre_since_confirmed,pre_pterm,pre_fterm,pre_till_pclose,pre_till_fclose,pre_loans_credit_limit,pre_loans_next_pay_summ,pre_loans_outstanding,pre_loans_total_overdue,pre_loans_max_overdue_sum,pre_loans_credit_cost_rate,pre_loans5,pre_loans530,pre_loans3060,pre_loans6090,pre_loans90,is_zero_loans5,is_zero_loans530,is_zero_loans3060,is_zero_loans6090,is_zero_loans90,pre_util,pre_over2limit,pre_maxover2limit,is_zero_util,is_zero_over2limit,is_zero_maxover2limit,enc_paym_0,enc_paym_1,enc_paym_2,enc_paym_3,enc_paym_4,enc_paym_5,enc_paym_6,enc_paym_7,enc_paym_8,enc_paym_9,enc_paym_10,enc_paym_11,enc_paym_12,enc_paym_13,enc_paym_14,enc_paym_15,enc_paym_16,enc_paym_17,enc_paym_18,enc_paym_19,enc_paym_20,enc_paym_21,enc_paym_22,enc_paym_23,enc_paym_24,enc_loans_account_holder_type,enc_loans_credit_status,enc_loans_credit_type,enc_loans_account_cur,pclose_flag,fclose_flag,flag
0,1678548,3,8,7,17,16,9,1,9,2,3,0,2,2,6,16,5,4,8,1,1,1,1,1,16,2,17,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,1,3,2,1,0,0,0
1,2834188,11,3,2,0,7,14,8,2,5,1,0,2,13,6,16,5,4,8,1,0,1,1,1,1,2,17,0,1,1,0,0,0,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,1,2,4,1,0,0,0
2,811902,11,9,6,11,13,14,8,2,5,1,0,2,11,6,16,5,4,8,1,1,1,1,1,11,2,17,0,1,1,0,0,0,0,0,0,0,0,3,3,3,4,3,3,3,3,3,3,3,3,4,3,3,3,4,1,2,4,1,0,0,0
3,836450,1,16,0,13,0,4,9,5,2,3,0,2,2,6,16,5,4,8,1,1,1,1,1,16,2,17,1,1,1,0,0,0,0,0,0,0,0,0,0,0,4,3,3,3,3,3,3,3,3,4,3,3,3,4,1,3,4,1,0,0,0
4,1769024,15,9,9,4,8,1,11,1,2,3,0,2,2,6,16,5,4,8,1,1,1,1,1,16,2,17,1,1,1,0,0,0,0,0,0,0,0,0,0,3,4,3,3,3,3,3,3,3,3,4,3,3,3,4,1,2,4,1,1,1,0

In [5]:
train.shape

(17659833, 62)

In [14]:
train.isna().sum().sort_values(ascending=False)
#ON constate qu'il n'y pas de valeurs manquantes

id                       0
rn                       0
pre_since_opened         0
pre_since_confirmed      0
pre_pterm                0
                        ..
enc_loans_credit_type    0
enc_loans_account_cur    0
pclose_flag              0
fclose_flag              0
flag                     0
Length: 62, dtype: int64

### 2.1 Columns Analysis

In [15]:
train.columns

Index(['id', 'rn', 'pre_since_opened', 'pre_since_confirmed', 'pre_pterm',
       'pre_fterm', 'pre_till_pclose', 'pre_till_fclose',
       'pre_loans_credit_limit', 'pre_loans_next_pay_summ',
       'pre_loans_outstanding', 'pre_loans_total_overdue',
       'pre_loans_max_overdue_sum', 'pre_loans_credit_cost_rate', 'pre_loans5',
       'pre_loans530', 'pre_loans3060', 'pre_loans6090', 'pre_loans90',
       'is_zero_loans5', 'is_zero_loans530', 'is_zero_loans3060',
       'is_zero_loans6090', 'is_zero_loans90', 'pre_util', 'pre_over2limit',
       'pre_maxover2limit', 'is_zero_util', 'is_zero_over2limit',
       'is_zero_maxover2limit', 'enc_paym_0', 'enc_paym_1', 'enc_paym_2',
       'enc_paym_3', 'enc_paym_4', 'enc_paym_5', 'enc_paym_6', 'enc_paym_7',
       'enc_paym_8', 'enc_paym_9', 'enc_paym_10', 'enc_paym_11', 'enc_paym_12',
       'enc_paym_13', 'enc_paym_14', 'enc_paym_15', 'enc_paym_16',
       'enc_paym_17', 'enc_paym_18', 'enc_paym_19', 'enc_paym_20',
       'enc_paym_21', 'enc_paym_22', 'enc_paym_23', 'enc_paym_24',
       'enc_loans_account_holder_type', 'enc_loans_credit_status',
       'enc_loans_credit_type', 'enc_loans_account_cur', 'pclose_flag',
       'fclose_flag', 'flag'],
      dtype='object')

In [16]:
train['rn'].value_counts()

rn
1     2024234
2     1876171
3     1721621
4     1566205
5     1413568
6     1267150
7     1126682
8      994369
9      873821
10     763014
11     663387
12     573519
13     495054
14     425391
15     365126
16     308955
17     258978
18     212703
19     172044
20     135811
21     105942
22      80790
23      61502
24      45856
25      34113
26      25252
27      18630
28      13752
29      10165
30       7536
31       5454
32       3868
33       2870
34       2043
35       1364
36        966
37        651
38        440
39        295
40        186
41        121
42         87
43         44
44         27
45         19
46         11
47         10
49          7
48          7
50          6
51          5
54          3
52          2
53          2
57          1
56          1
55          1
58          1
Name: count, dtype: int64

## Conclusion  : 
Après une analyse détaillée des colonnes du dataset, nous constatons que la plupart d'entre elles, bien que numériques ou ordinales présentent une structure similaire à celle de variables catégorielles à haute cardinalité, avec une distribution hautement déséquilibrée.

Dans la suite de notre pipeline, nous procéderons à un entraînement sans suppression de données pour préserver l'intégralité des signaux prédictifs, en nous appuyant sur une régularisation renforcée ; toutefois, si les performances sur la validation ou la soumission en ligne s'avèrent insuffisantes,nous reviendrons sur cette approche en supprimant sélectivement des lignes  ou des colonnes à faible valeur ajoutée .

## 2.2 Is columns Id unique ?

In [17]:
train.shape

(17659833, 62)

In [20]:
len(train["id"].unique())

2892602

## Conclusion 
Après une première inspection du dataset, nous constatons que la table d'entraînement est de taille considérable, avec 17,6 millions de lignes et 62 colonnes, reflétant un historique exhaustif de transactions de crédit. Cependant, une analyse plus approfondie révèle que de nombreux clients (identifiés par l'id) peuvent contracter plusieurs prêts au cours du temps, générant ainsi des redondances structurelles dans les données qui justifient une approche d'agrégation par client pour optimiser l'apprentissage sans perte d'information.

## 2.3 Feature Engineering

In [2]:
def create_global_aggregations_train_test(train, test):
    """
    Crée les agrégations GLOBALES :
    - Fit sur TRAIN uniquement
    - Transform sur TEST (même stats que train)
    """
    # 1. Calcul des agrégations sur TRAIN
    agg_dict = {
        'rn': 'max',
        'pre_loans_credit_limit': ['mean', 'min', 'max', 'std', 'sum'],
        'pre_loans_outstanding': ['sum', 'mean', 'max'],
        'pre_loans_max_overdue_sum': ['max', 'mean', 'sum'],
        'pre_loans_total_overdue': ['sum', 'max', 'mean'],
        'pre_loans_credit_cost_rate': ['mean', 'std', 'min', 'max'],
        'pre_loans_next_pay_summ': ['sum', 'mean', 'max'],
    }
    
    train_agg = train.groupby('id').agg(agg_dict).reset_index()
    train_agg.columns = [
        'id', 'total_loans',
        'avg_credit_limit', 'min_credit_limit', 'max_credit_limit', 'std_credit_limit', 'sum_credit_limit',
        'total_outstanding', 'avg_outstanding', 'max_outstanding',
        'max_overdue_ever', 'avg_max_overdue', 'total_max_overdue',
        'total_overdue_current', 'max_overdue_current', 'avg_overdue_current',
        'avg_credit_cost_rate', 'std_credit_cost_rate', 'min_credit_cost_rate', 'max_credit_cost_rate',
        'total_next_pay_summ', 'avg_next_pay_summ', 'max_next_pay_summ'
    ]
    
    # Remplacer std NaN par 0
    std_cols = [c for c in train_agg.columns if c.startswith('std_')]
    train_agg[std_cols] = train_agg[std_cols].fillna(0)
    
    # 2. Appliquer les mêmes stats au TEST
    test_agg = test[['id']].merge(train_agg, on='id', how='left')
    
    # Pour les clients ABSENTS du train → imputer avec les moyennes du train
    global_means = train_agg.drop(columns='id').mean()
    test_agg = test_agg.fillna(global_means)
    
    return train_agg, test_agg

In [ ]:
# === 2. Créer les features SANS leakage ===
train_agg, test_agg = create_global_aggregations_train_test(train, test)

# === 3. Enrichir ===
train_enriched = train.merge(train_agg, on='id', how='left')
test_enriched = test.merge(test_agg, on='id', how='left')

# === 4. Nettoyage mémoire ===
del train, test, train_agg, test_agg
gc.collect()

#  3. Model Training

In [ ]:

drop_cols = ['id', 'rn', 'flag']
X = train_enriched.drop(columns=drop_cols)
y = train_enriched['flag']

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [ ]:
    loss_function='Logloss',
    eval_metric='AUC',
    task_type="GPU",
    devices='0',
    
    depth=6,
    iterations=200000,
    learning_rate=0.05,
    l2_leaf_reg=10,
    border_count=128,
    bootstrap_type='Bernoulli',   
    subsample=0.8,
    
    auto_class_weights='Balanced',
    early_stopping_rounds=200,
    use_best_model=True,
    random_seed=42,
    verbose=100,
)

In [4]:
#Attendre 9h sous GPU
print("Entraînement sur GPU...")
model.fit(X_train, y_train, eval_set=(X_val, y_val), verbose=100)

Entraînement sur GPU...

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6081305	best: 0.6081305 (0)	total: 198ms	remaining: 11h 1m 30s
100:	test: 0.6574856	best: 0.6574856 (100)	total: 16.9s	remaining: 9h 18m 22s
200:	test: 0.6680968	best: 0.6680968 (200)	total: 33.2s	remaining: 9h 10m 26s
300:	test: 0.6746226	best: 0.6746226 (300)	total: 49.8s	remaining: 9h 10m 14s
400:	test: 0.6793954	best: 0.6793954 (400)	total: 1m 6s	remaining: 9h 9m 2s
500:	test: 0.6829485	best: 0.6829485 (500)	total: 1m 22s	remaining: 9h 7m 24s
600:	test: 0.6862406	best: 0.6862406 (600)	total: 1m 38s	remaining: 9h 5m 54s
700:	test: 0.6893761	best: 0.6893761 (700)	total: 1m 54s	remaining: 9h 4m 35s
800:	test: 0.6922550	best: 0.6922550 (800)	total: 2m 11s	remaining: 9h 3m 20s
900:	test: 0.6948094	best: 0.6948094 (900)	total: 2m 27s	remaining: 9h 2m 24s
1000:	test: 0.6974188	best: 0.6974188 (1000)	total: 2m 43s	remaining: 9h 2m 14s
1100:	test: 0.6994663	best: 0.6994663 (1100)	total: 2m 59s	remaining: 9h 1m 9s
1200:	test: 0.7013940	best: 0.7013940 (1200)	total: 3m 16s	remaining: 9h 48s
1300:	test: 0.7038805	best: 0.7038805 (1300)	total: 3m 32s	remaining: 9h 10s
1400:	test: 0.7059229	best: 0.7059229 (1400)	total: 3m 48s	remaining: 8h 59m 46s
1500:	test: 0.7082750	best: 0.7082750 (1500)	total: 4m 4s	remaining: 8h 59m 18s
1600:	test: 0.7102518	best: 0.7102518 (1600)	total: 4m 20s	remaining: 8h 58m 46s
1700:	test: 0.7123184	best: 0.7123184 (1700)	total: 4m 37s	remaining: 8h 58m 31s
1800:	test: 0.7141368	best: 0.7141368 (1800)	total: 4m 53s	remaining: 8h 58m 12s
1900:	test: 0.7158529	best: 0.7158529 (1900)	total: 5m 9s	remaining: 8h 58m 8s
2000:	test: 0.7176745	best: 0.7176745 (2000)	total: 5m 26s	remaining: 8h 57m 51s
2100:	test: 0.7195806	best: 0.7195806 (2100)	total: 5m 42s	remaining: 8h 57m 56s
2200:	test: 0.7212402	best: 0.7212402 (2200)	total: 5m 59s	remaining: 8h 57m 49s
2300:	test: 0.7229163	best: 0.7229163 (2300)	total: 6m 15s	remaining: 8h 57m 39s
2400:	test: 0.7244922	best: 0.7244922 (2400)	total: 6m 32s	remaining: 8h 57m 41s
2500:	test: 0.7259396	best: 0.7259396 (2500)	total: 6m 48s	remaining: 8h 57m 36s
2600:	test: 0.7274799	best: 0.7274799 (2600)	total: 7m 4s	remaining: 8h 57m 18s
2700:	test: 0.7289447	best: 0.7289447 (2700)	total: 7m 20s	remaining: 8h 56m 50s
2800:	test: 0.7302096	best: 0.7302096 (2800)	total: 7m 37s	remaining: 8h 56m 27s
2900:	test: 0.7316681	best: 0.7316681 (2900)	total: 7m 53s	remaining: 8h 56m 12s
3000:	test: 0.7330237	best: 0.7330237 (3000)	total: 8m 9s	remaining: 8h 56m 2s
3100:	test: 0.7343425	best: 0.7343425 (3100)	total: 8m 26s	remaining: 8h 55m 53s
3200:	test: 0.7357785	best: 0.7357785 (3200)	total: 8m 42s	remaining: 8h 55m 35s
3300:	test: 0.7371411	best: 0.7371411 (3300)	total: 8m 59s	remaining: 8h 55m 33s
3400:	test: 0.7385715	best: 0.7385715 (3400)	total: 9m 15s	remaining: 8h 55m 17s
3500:	test: 0.7396817	best: 0.7396817 (3500)	total: 9m 31s	remaining: 8h 55m
3600:	test: 0.7409855	best: 0.7409855 (3600)	total: 9m 48s	remaining: 8h 54m 40s
3700:	test: 0.7422670	best: 0.7422670 (3700)	total: 10m 4s	remaining: 8h 54m 28s
3800:	test: 0.7435664	best: 0.7435664 (3800)	total: 10m 21s	remaining: 8h 54m 15s
3900:	test: 0.7445835	best: 0.7445835 (3900)	total: 10m 37s	remaining: 8h 54m 3s
4000:	test: 0.7458085	best: 0.7458102 (3998)	total: 10m 53s	remaining: 8h 53m 47s
4100:	test: 0.7469105	best: 0.7469105 (4100)	total: 11m 10s	remaining: 8h 53m 36s
4200:	test: 0.7480491	best: 0.7480491 (4200)	total: 11m 26s	remaining: 8h 53m 20s
4300:	test: 0.7491565	best: 0.7491565 (4300)	total: 11m 43s	remaining: 8h 53m 8s
4400:	test: 0.7501787	best: 0.7501787 (4400)	total: 11m 59s	remaining: 8h 52m 57s
4500:	test: 0.7513309	best: 0.7513309 (4500)	total: 12m 15s	remaining: 8h 52m 46s
4600:	test: 0.7523955	best: 0.7523955 (4600)	total: 12m 32s	remaining: 8h 52m 32s
4700:	test: 0.7535159	best: 0.7535159 (4700)	total: 12m 48s	remaining: 8h 52m 20s
4800:	test: 0.7545909	best: 0.7545909 (4800)	total: 13m 5s	remaining: 8h 52m 1s
4900:	test: 0.7556435	best: 0.7556435 (4900)	total: 13m 21s	remaining: 8h 51m 55s
5000:	test: 0.7566022	best: 0.7566022 (5000)	total: 13m 38s	remaining: 8h 51m 41s
5100:	test: 0.7575457	best: 0.7575457 (5100)	total: 13m 54s	remaining: 8h 51m 24s
5200:	test: 0.7585119	best: 0.7585119 (5200)	total: 14m 10s	remaining: 8h 51m 13s
5300:	test: 0.7594835	best: 0.7594842 (5299)	total: 14m 27s	remaining: 8h 50m 58s
5400:	test: 0.7603947	best: 0.7603947 (5400)	total: 14m 43s	remaining: 8h 50m 41s
5500:	test: 0.7613386	best: 0.7613386 (5500)	total: 15m	remaining: 8h 50m 29s
5600:	test: 0.7623512	best: 0.7623512 (5600)	total: 15m 16s	remaining: 8h 50m 17s
5700:	test: 0.7633538	best: 0.7633538 (5700)	total: 15m 33s	remaining: 8h 50m 3s
5800:	test: 0.7644629	best: 0.7644629 (5800)	total: 15m 49s	remaining: 8h 49m 43s
5900:	test: 0.7654141	best: 0.7654141 (5900)	total: 16m 5s	remaining: 8h 49m 31s
6000:	test: 0.7663222	best: 0.7663222 (6000)	total: 16m 22s	remaining: 8h 49m 18s
6100:	test: 0.7673723	best: 0.7673723 (6100)	total: 16m 38s	remaining: 8h 49m 6s
6200:	test: 0.7683263	best: 0.7683272 (6199)	total: 16m 55s	remaining: 8h 48m 51s
6300:	test: 0.7692398	best: 0.7692398 (6300)	total: 17m 11s	remaining: 8h 48m 37s
6400:	test: 0.7701848	best: 0.7701848 (6400)	total: 17m 28s	remaining: 8h 48m 25s
6500:	test: 0.7711505	best: 0.7711505 (6500)	total: 17m 44s	remaining: 8h 48m 14s
6600:	test: 0.7720539	best: 0.7720539 (6600)	total: 18m 1s	remaining: 8h 48m 4s
6700:	test: 0.7731994	best: 0.7731994 (6700)	total: 18m 17s	remaining: 8h 47m 52s
6800:	test: 0.7742978	best: 0.7742978 (6800)	total: 18m 34s	remaining: 8h 47m 37s
6900:	test: 0.7752470	best: 0.7752470 (6900)	total: 18m 50s	remaining: 8h 47m 18s
7000:	test: 0.7760840	best: 0.7760840 (7000)	total: 19m 6s	remaining: 8h 46m 59s
7100:	test: 0.7767797	best: 0.7767797 (7100)	total: 19m 23s	remaining: 8h 46m 47s
7200:	test: 0.7776036	best: 0.7776036 (7200)	total: 19m 39s	remaining: 8h 46m 32s
7300:	test: 0.7784626	best: 0.7784626 (7300)	total: 19m 56s	remaining: 8h 46m 22s
7400:	test: 0.7792832	best: 0.7792832 (7400)	total: 20m 13s	remaining: 8h 46m 6s
7500:	test: 0.7800728	best: 0.7800728 (7500)	total: 20m 29s	remaining: 8h 45m 51s
7600:	test: 0.7810848	best: 0.7810848 (7600)	total: 20m 45s	remaining: 8h 45m 38s
7700:	test: 0.7819218	best: 0.7819218 (7700)	total: 21m 2s	remaining: 8h 45m 21s
7800:	test: 0.7827381	best: 0.7827381 (7800)	total: 21m 18s	remaining: 8h 45m 6s
7900:	test: 0.7834626	best: 0.7834626 (7900)	total: 21m 35s	remaining: 8h 44m 51s
8000:	test: 0.7842286	best: 0.7842286 (8000)	total: 21m 51s	remaining: 8h 44m 31s
8100:	test: 0.7851003	best: 0.7851003 (8100)	total: 22m 7s	remaining: 8h 44m 12s
8200:	test: 0.7858908	best: 0.7858908 (8200)	total: 22m 24s	remaining: 8h 43m 56s
8300:	test: 0.7865696	best: 0.7865696 (8300)	total: 22m 40s	remaining: 8h 43m 47s
8400:	test: 0.7873567	best: 0.7873567 (8400)	total: 22m 57s	remaining: 8h 43m 28s
8500:	test: 0.7882317	best: 0.7882317 (8500)	total: 23m 13s	remaining: 8h 43m 10s
8600:	test: 0.7889358	best: 0.7889358 (8600)	total: 23m 29s	remaining: 8h 42m 56s
8700:	test: 0.7895910	best: 0.7895910 (8700)	total: 23m 46s	remaining: 8h 42m 40s
8800:	test: 0.7904634	best: 0.7904634 (8800)	total: 24m 2s	remaining: 8h 42m 25s
8900:	test: 0.7912771	best: 0.7912771 (8900)	total: 24m 19s	remaining: 8h 42m 9s
9000:	test: 0.7919470	best: 0.7919470 (9000)	total: 24m 35s	remaining: 8h 41m 54s
9100:	test: 0.7925593	best: 0.7925598 (9099)	total: 24m 52s	remaining: 8h 41m 39s
9200:	test: 0.7931793	best: 0.7931793 (9200)	total: 25m 8s	remaining: 8h 41m 19s
9300:	test: 0.7938064	best: 0.7938064 (9300)	total: 25m 24s	remaining: 8h 41m 2s
9400:	test: 0.7945086	best: 0.7945086 (9400)	total: 25m 41s	remaining: 8h 40m 47s
9500:	test: 0.7951166	best: 0.7951166 (9500)	total: 25m 57s	remaining: 8h 40m 30s
9600:	test: 0.7957468	best: 0.7957468 (9600)	total: 26m 14s	remaining: 8h 40m 14s
9700:	test: 0.7964437	best: 0.7964437 (9700)	total: 26m 30s	remaining: 8h 39m 59s
9800:	test: 0.7971902	best: 0.7971902 (9800)	total: 26m 46s	remaining: 8h 39m 41s
9900:	test: 0.7978860	best: 0.7978860 (9900)	total: 27m 3s	remaining: 8h 39m 28s
10000:	test: 0.7985131	best: 0.7985131 (10000)	total: 27m 19s	remaining: 8h 39m 15s
10100:	test: 0.7991430	best: 0.7991430 (10100)	total: 27m 36s	remaining: 8h 39m
10200:	test: 0.7998186	best: 0.7998186 (10200)	total: 27m 52s	remaining: 8h 38m 44s
10300:	test: 0.8006448	best: 0.8006448 (10300)	total: 28m 9s	remaining: 8h 38m 25s
10400:	test: 0.8013741	best: 0.8013745 (10399)	total: 28m 25s	remaining: 8h 38m 11s
10500:	test: 0.8020976	best: 0.8020976 (10500)	total: 28m 42s	remaining: 8h 37m 56s
10600:	test: 0.8027660	best: 0.8027660 (10600)	total: 28m 58s	remaining: 8h 37m 43s
10700:	test: 0.8034275	best: 0.8034275 (10700)	total: 29m 15s	remaining: 8h 37m 31s
10800:	test: 0.8039963	best: 0.8039963 (10800)	total: 29m 31s	remaining: 8h 37m 12s
10900:	test: 0.8046564	best: 0.8046564 (10899)	total: 29m 48s	remaining: 8h 36m 59s
11000:	test: 0.8052519	best: 0.8052519 (11000)	total: 30m 4s	remaining: 8h 36m 44s
11100:	test: 0.8059270	best: 0.8059270 (11100)	total: 30m 21s	remaining: 8h 36m 30s
11200:	test: 0.8065348	best: 0.8065348 (11200)	total: 30m 37s	remaining: 8h 36m 15s
11300:	test: 0.8072106	best: 0.8072106 (11300)	total: 30m 54s	remaining: 8h 36m
11400:	test: 0.8078052	best: 0.8078052 (11400)	total: 31m 10s	remaining: 8h 35m 47s
11500:	test: 0.8083532	best: 0.8083532 (11500)	total: 31m 27s	remaining: 8h 35m 29s
11600:	test: 0.8090274	best: 0.8090274 (11600)	total: 31m 43s	remaining: 8h 35m 14s
11700:	test: 0.8096216	best: 0.8096216 (11700)	total: 32m	remaining: 8h 35m
11800:	test: 0.8101977	best: 0.8101977 (11800)	total: 32m 16s	remaining: 8h 34m 48s
11900:	test: 0.8108504	best: 0.8108504 (11900)	total: 32m 33s	remaining: 8h 34m 34s
12000:	test: 0.8114063	best: 0.8114063 (12000)	total: 32m 49s	remaining: 8h 34m 18s
12100:	test: 0.8119125	best: 0.8119125 (12100)	total: 33m 6s	remaining: 8h 34m 3s
12200:	test: 0.8125251	best: 0.8125251 (12200)	total: 33m 22s	remaining: 8h 33m 45s
12300:	test: 0.8130443	best: 0.8130443 (12300)	total: 33m 39s	remaining: 8h 33m 28s
12400:	test: 0.8135332	best: 0.8135332 (12400)	total: 33m 55s	remaining: 8h 33m 12s
12500:	test: 0.8140597	best: 0.8140610 (12499)	total: 34m 11s	remaining: 8h 32m 56s
12600:	test: 0.8145753	best: 0.8145753 (12600)	total: 34m 28s	remaining: 8h 32m 38s
12700:	test: 0.8151065	best: 0.8151069 (12699)	total: 34m 44s	remaining: 8h 32m 23s
12800:	test: 0.8156385	best: 0.8156385 (12800)	total: 35m 1s	remaining: 8h 32m 6s
12900:	test: 0.8161912	best: 0.8161912 (12900)	total: 35m 17s	remaining: 8h 31m 53s
13000:	test: 0.8166594	best: 0.8166594 (13000)	total: 35m 34s	remaining: 8h 31m 35s
13100:	test: 0.8171344	best: 0.8171344 (13100)	total: 35m 50s	remaining: 8h 31m 20s
13200:	test: 0.8176190	best: 0.8176190 (13200)	total: 36m 6s	remaining: 8h 31m 2s
13300:	test: 0.8181450	best: 0.8181450 (13300)	total: 36m 23s	remaining: 8h 30m 46s
13400:	test: 0.8186350	best: 0.8186350 (13400)	total: 36m 39s	remaining: 8h 30m 32s
13500:	test: 0.8191626	best: 0.8191626 (13500)	total: 36m 56s	remaining: 8h 30m 15s
13600:	test: 0.8196965	best: 0.8196968 (13599)	total: 37m 12s	remaining: 8h 29m 58s
13700:	test: 0.8203381	best: 0.8203386 (13699)	total: 37m 29s	remaining: 8h 29m 43s
13800:	test: 0.8208851	best: 0.8208851 (13800)	total: 37m 45s	remaining: 8h 29m 29s
13900:	test: 0.8213801	best: 0.8213801 (13899)	total: 38m 2s	remaining: 8h 29m 14s
14000:	test: 0.8219699	best: 0.8219699 (14000)	total: 38m 18s	remaining: 8h 28m 59s
14100:	test: 0.8224720	best: 0.8224730 (14099)	total: 38m 35s	remaining: 8h 28m 45s
14200:	test: 0.8229963	best: 0.8229976 (14199)	total: 38m 52s	remaining: 8h 28m 32s
14300:	test: 0.8234264	best: 0.8234264 (14300)	total: 39m 8s	remaining: 8h 28m 15s
14400:	test: 0.8240277	best: 0.8240277 (14400)	total: 39m 24s	remaining: 8h 27m 58s
14500:	test: 0.8246148	best: 0.8246148 (14500)	total: 39m 41s	remaining: 8h 27m 44s
14600:	test: 0.8251007	best: 0.8251007 (14600)	total: 39m 58s	remaining: 8h 27m 29s
14700:	test: 0.8255892	best: 0.8255892 (14700)	total: 40m 14s	remaining: 8h 27m 14s
14800:	test: 0.8261089	best: 0.8261089 (14800)	total: 40m 31s	remaining: 8h 26m 59s
14900:	test: 0.8266714	best: 0.8266714 (14900)	total: 40m 47s	remaining: 8h 26m 46s
15000:	test: 0.8271694	best: 0.8271694 (15000)	total: 41m 4s	remaining: 8h 26m 32s
15100:	test: 0.8277082	best: 0.8277082 (15100)	total: 41m 20s	remaining: 8h 26m 15s
15200:	test: 0.8281566	best: 0.8281566 (15200)	total: 41m 37s	remaining: 8h 26m
15300:	test: 0.8285891	best: 0.8285891 (15300)	total: 41m 53s	remaining: 8h 25m 42s
15400:	test: 0.8289714	best: 0.8289724 (15399)	total: 42m 10s	remaining: 8h 25m 25s
15500:	test: 0.8293477	best: 0.8293477 (15500)	total: 42m 26s	remaining: 8h 25m 5s
15600:	test: 0.8298092	best: 0.8298092 (15600)	total: 42m 42s	remaining: 8h 24m 49s
15700:	test: 0.8302581	best: 0.8302581 (15700)	total: 42m 58s	remaining: 8h 24m 31s
15800:	test: 0.8307057	best: 0.8307057 (15800)	total: 43m 15s	remaining: 8h 24m 15s
15900:	test: 0.8311635	best: 0.8311639 (15898)	total: 43m 31s	remaining: 8h 23m 58s
16000:	test: 0.8316608	best: 0.8316608 (16000)	total: 43m 48s	remaining: 8h 23m 41s
16100:	test: 0.8320827	best: 0.8320847 (16099)	total: 44m 4s	remaining: 8h 23m 24s
16200:	test: 0.8325130	best: 0.8325130 (16200)	total: 44m 20s	remaining: 8h 23m 8s
16300:	test: 0.8329930	best: 0.8329930 (16300)	total: 44m 37s	remaining: 8h 22m 51s
16400:	test: 0.8333458	best: 0.8333458 (16400)	total: 44m 53s	remaining: 8h 22m 33s
16500:	test: 0.8337827	best: 0.8337827 (16500)	total: 45m 9s	remaining: 8h 22m 15s
16600:	test: 0.8341941	best: 0.8341941 (16600)	total: 45m 26s	remaining: 8h 21m 55s
16700:	test: 0.8345752	best: 0.8345752 (16700)	total: 45m 42s	remaining: 8h 21m 40s
16800:	test: 0.8349960	best: 0.8349960 (16800)	total: 45m 58s	remaining: 8h 21m 23s
16900:	test: 0.8354019	best: 0.8354019 (16900)	total: 46m 15s	remaining: 8h 21m 6s
17000:	test: 0.8358572	best: 0.8358572 (17000)	total: 46m 31s	remaining: 8h 20m 47s
17100:	test: 0.8362951	best: 0.8362951 (17100)	total: 46m 47s	remaining: 8h 20m 32s
17200:	test: 0.8367469	best: 0.8367471 (17199)	total: 47m 4s	remaining: 8h 20m 15s
17300:	test: 0.8371401	best: 0.8371401 (17300)	total: 47m 20s	remaining: 8h 19m 55s
17400:	test: 0.8375610	best: 0.8375610 (17400)	total: 47m 36s	remaining: 8h 19m 37s
17500:	test: 0.8379989	best: 0.8379989 (17500)	total: 47m 53s	remaining: 8h 19m 20s
17600:	test: 0.8384413	best: 0.8384413 (17600)	total: 48m 9s	remaining: 8h 19m 4s
17700:	test: 0.8388826	best: 0.8388826 (17700)	total: 48m 25s	remaining: 8h 18m 47s
17800:	test: 0.8392782	best: 0.8392782 (17800)	total: 48m 42s	remaining: 8h 18m 30s
17900:	test: 0.8397638	best: 0.8397638 (17900)	total: 48m 58s	remaining: 8h 18m 13s
18000:	test: 0.8401638	best: 0.8401646 (17999)	total: 49m 14s	remaining: 8h 17m 55s
18100:	test: 0.8405980	best: 0.8405980 (18100)	total: 49m 31s	remaining: 8h 17m 38s
18200:	test: 0.8409749	best: 0.8409749 (18200)	total: 49m 47s	remaining: 8h 17m 21s
18300:	test: 0.8413657	best: 0.8413657 (18300)	total: 50m 4s	remaining: 8h 17m 6s
18400:	test: 0.8417723	best: 0.8417723 (18400)	total: 50m 20s	remaining: 8h 16m 50s
18500:	test: 0.8420842	best: 0.8420842 (18500)	total: 50m 36s	remaining: 8h 16m 31s
18600:	test: 0.8424500	best: 0.8424500 (18600)	total: 50m 52s	remaining: 8h 16m 12s
18700:	test: 0.8428748	best: 0.8428748 (18700)	total: 51m 9s	remaining: 8h 15m 55s
18800:	test: 0.8432575	best: 0.8432575 (18800)	total: 51m 25s	remaining: 8h 15m 39s
18900:	test: 0.8436345	best: 0.8436345 (18900)	total: 51m 42s	remaining: 8h 15m 23s
19000:	test: 0.8440058	best: 0.8440058 (19000)	total: 51m 58s	remaining: 8h 15m 4s
19100:	test: 0.8443488	best: 0.8443488 (19098)	total: 52m 14s	remaining: 8h 14m 49s
19200:	test: 0.8447047	best: 0.8447047 (19200)	total: 52m 31s	remaining: 8h 14m 30s
19300:	test: 0.8450940	best: 0.8450940 (19300)	total: 52m 47s	remaining: 8h 14m 13s
19400:	test: 0.8454645	best: 0.8454645 (19400)	total: 53m 3s	remaining: 8h 13m 56s
19500:	test: 0.8458585	best: 0.8458585 (19500)	total: 53m 20s	remaining: 8h 13m 41s
19600:	test: 0.8462239	best: 0.8462239 (19600)	total: 53m 36s	remaining: 8h 13m 23s
19700:	test: 0.8465629	best: 0.8465629 (19700)	total: 53m 52s	remaining: 8h 13m 6s
19800:	test: 0.8468786	best: 0.8468797 (19797)	total: 54m 9s	remaining: 8h 12m 48s
19900:	test: 0.8473201	best: 0.8473201 (19900)	total: 54m 25s	remaining: 8h 12m 31s
20000:	test: 0.8477053	best: 0.8477053 (20000)	total: 54m 41s	remaining: 8h 12m 13s
20100:	test: 0.8480292	best: 0.8480292 (20100)	total: 54m 57s	remaining: 8h 11m 55s
20200:	test: 0.8484814	best: 0.8484814 (20200)	total: 55m 14s	remaining: 8h 11m 39s
20300:	test: 0.8488754	best: 0.8488754 (20300)	total: 55m 30s	remaining: 8h 11m 22s
20400:	test: 0.8492654	best: 0.8492657 (20399)	total: 55m 46s	remaining: 8h 11m 4s
20500:	test: 0.8496177	best: 0.8496177 (20500)	total: 56m 3s	remaining: 8h 10m 48s
20600:	test: 0.8500142	best: 0.8500142 (20600)	total: 56m 19s	remaining: 8h 10m 30s
20700:	test: 0.8503026	best: 0.8503026 (20700)	total: 56m 36s	remaining: 8h 10m 15s
20800:	test: 0.8506008	best: 0.8506008 (20800)	total: 56m 52s	remaining: 8h 9m 56s
20900:	test: 0.8509370	best: 0.8509370 (20900)	total: 57m 8s	remaining: 8h 9m 40s
21000:	test: 0.8513057	best: 0.8513057 (21000)	total: 57m 25s	remaining: 8h 9m 25s
21100:	test: 0.8516905	best: 0.8516905 (21100)	total: 57m 41s	remaining: 8h 9m 8s
21200:	test: 0.8520489	best: 0.8520489 (21200)	total: 57m 58s	remaining: 8h 8m 53s
21300:	test: 0.8523535	best: 0.8523541 (21299)	total: 58m 14s	remaining: 8h 8m 36s
21400:	test: 0.8527358	best: 0.8527367 (21399)	total: 58m 31s	remaining: 8h 8m 20s
21500:	test: 0.8530760	best: 0.8530760 (21500)	total: 58m 47s	remaining: 8h 8m 4s
21600:	test: 0.8533857	best: 0.8533857 (21600)	total: 59m 3s	remaining: 8h 7m 47s
21700:	test: 0.8536901	best: 0.8536901 (21700)	total: 59m 20s	remaining: 8h 7m 29s
21800:	test: 0.8540865	best: 0.8540865 (21800)	total: 59m 36s	remaining: 8h 7m 13s
21900:	test: 0.8544181	best: 0.8544181 (21900)	total: 59m 52s	remaining: 8h 6m 57s
22000:	test: 0.8547795	best: 0.8547795 (22000)	total: 1h 9s	remaining: 8h 6m 40s
22100:	test: 0.8551230	best: 0.8551230 (22100)	total: 1h 25s	remaining: 8h 6m 23s
22200:	test: 0.8555139	best: 0.8555139 (22200)	total: 1h 41s	remaining: 8h 6m 6s
22300:	test: 0.8558630	best: 0.8558630 (22300)	total: 1h 58s	remaining: 8h 5m 49s
22400:	test: 0.8562293	best: 0.8562293 (22400)	total: 1h 1m 14s	remaining: 8h 5m 32s
22500:	test: 0.8565472	best: 0.8565472 (22500)	total: 1h 1m 30s	remaining: 8h 5m 14s
22600:	test: 0.8568591	best: 0.8568591 (22600)	total: 1h 1m 47s	remaining: 8h 4m 57s
22700:	test: 0.8571669	best: 0.8571678 (22698)	total: 1h 2m 3s	remaining: 8h 4m 41s
22800:	test: 0.8575305	best: 0.8575309 (22799)	total: 1h 2m 19s	remaining: 8h 4m 24s
22900:	test: 0.8578814	best: 0.8578814 (22900)	total: 1h 2m 36s	remaining: 8h 4m 8s
23000:	test: 0.8582173	best: 0.8582173 (23000)	total: 1h 2m 52s	remaining: 8h 3m 51s
23100:	test: 0.8585092	best: 0.8585092 (23100)	total: 1h 3m 8s	remaining: 8h 3m 34s
23200:	test: 0.8588899	best: 0.8588899 (23200)	total: 1h 3m 25s	remaining: 8h 3m 16s
23300:	test: 0.8591873	best: 0.8591873 (23300)	total: 1h 3m 41s	remaining: 8h 2m 59s
23400:	test: 0.8595050	best: 0.8595050 (23400)	total: 1h 3m 57s	remaining: 8h 2m 42s
23500:	test: 0.8598378	best: 0.8598378 (23500)	total: 1h 4m 14s	remaining: 8h 2m 25s
23600:	test: 0.8601492	best: 0.8601492 (23600)	total: 1h 4m 30s	remaining: 8h 2m 9s
23700:	test: 0.8604807	best: 0.8604807 (23700)	total: 1h 4m 46s	remaining: 8h 1m 53s
23800:	test: 0.8608028	best: 0.8608028 (23800)	total: 1h 5m 3s	remaining: 8h 1m 36s
23900:	test: 0.8610765	best: 0.8610782 (23899)	total: 1h 5m 19s	remaining: 8h 1m 20s
24000:	test: 0.8614513	best: 0.8614513 (24000)	total: 1h 5m 36s	remaining: 8h 1m 5s
24100:	test: 0.8617566	best: 0.8617566 (24100)	total: 1h 5m 52s	remaining: 8h 47s

# 4 Evaluation

In [5]:
# === 7. Évaluation ===
train_preds = model.predict_proba(X_train)[:, 1]
val_preds = model.predict_proba(X_val)[:, 1]
print(f"Train AUC: {roc_auc_score(y_train, train_preds):.6f}")
print(f"Val AUC: {roc_auc_score(y_val, val_preds):.6f}")

Train AUC: 0.996961
Val AUC: 0.967863

In [27]:
test_enriched.head()

,id,rn,pre_since_opened,pre_since_confirmed,pre_pterm,pre_fterm,pre_till_pclose,pre_till_fclose,pre_loans_credit_limit,pre_loans_next_pay_summ,pre_loans_outstanding,pre_loans_total_overdue,pre_loans_max_overdue_sum,pre_loans_credit_cost_rate,pre_loans5,pre_loans530,pre_loans3060,pre_loans6090,pre_loans90,is_zero_loans5,is_zero_loans530,is_zero_loans3060,is_zero_loans6090,is_zero_loans90,pre_util,pre_over2limit,pre_maxover2limit,is_zero_util,is_zero_over2limit,is_zero_maxover2limit,enc_paym_0,enc_paym_1,enc_paym_2,enc_paym_3,enc_paym_4,enc_paym_5,enc_paym_6,enc_paym_7,enc_paym_8,enc_paym_9,enc_paym_10,enc_paym_11,enc_paym_12,enc_paym_13,enc_paym_14,enc_paym_15,enc_paym_16,enc_paym_17,enc_paym_18,enc_paym_19,enc_paym_20,enc_paym_21,enc_paym_22,enc_paym_23,enc_paym_24,enc_loans_account_holder_type,enc_loans_credit_status,enc_loans_credit_type,enc_loans_account_cur,pclose_flag,fclose_flag,id_x_rn,total_loans,avg_credit_limit,min_credit_limit,max_credit_limit,std_credit_limit,sum_credit_limit,total_outstanding,avg_outstanding,max_outstanding,max_overdue_ever,avg_max_overdue,total_max_overdue,total_overdue_current,max_overdue_current,avg_overdue_current,avg_credit_cost_rate,std_credit_cost_rate,min_credit_cost_rate,max_credit_cost_rate,total_next_pay_summ,avg_next_pay_summ,max_next_pay_summ
0,1472943,2,10,4,16,16,13,10,10,2,3,0,2,2,6,16,5,4,8,1,1,1,1,1,16,2,17,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,3,3,3,3,3,4,3,3,3,4,1,3,4,1,0,0,1472943_x_2,9.0,9.833333,0.0,16.0,5.564770,59.0,20.0,3.333333,5.0,2.0,2.0,12.0,0.0,0.0,0.0,3.500000,3.674235,2.0,11.0,10.0,1.666667,2.0
1,660465,5,6,14,9,7,3,11,0,2,3,0,2,4,6,16,5,4,8,1,0,1,1,1,16,2,17,1,1,1,0,0,0,0,0,0,0,0,0,1,0,1,3,3,3,3,3,3,3,3,4,3,3,3,4,1,3,4,1,0,0,660465_x_5,4.0,4.000000,4.0,4.0,0.000000,4.0,3.0,3.000000,3.0,2.0,2.0,2.0,0.0,0.0,0.0,4.000000,0.000000,4.0,4.0,2.0,2.000000,2.0
2,1788193,3,1,0,9,9,7,2,16,2,3,0,2,2,6,16,5,4,8,1,1,1,1,1,16,2,17,1,1,1,0,0,0,0,0,0,0,0,0,0,0,4,3,3,3,3,3,3,3,3,4,3,3,3,4,1,3,4,1,0,0,1788193_x_3,4.0,8.333333,3.0,12.0,4.725816,25.0,9.0,3.000000,3.0,2.0,2.0,6.0,0.0,0.0,0.0,2.000000,0.000000,2.0,2.0,6.0,2.000000,2.0
3,2767146,3,15,8,1,16,6,13,14,2,3,0,2,2,6,16,5,4,8,1,1,1,1,1,9,5,4,0,0,0,0,0,3,3,3,3,3,3,3,3,3,4,3,3,3,3,3,3,3,3,4,3,3,3,4,1,3,3,1,0,0,2767146_x_3,20.0,9.750000,2.0,18.0,5.207076,117.0,36.0,3.000000,5.0,2.0,2.0,24.0,0.0,0.0,0.0,6.166667,5.457827,0.0,13.0,29.0,2.416667,6.0
4,2601698,9,19,10,4,8,1,11,4,2,3,0,2,2,6,16,5,4,8,1,1,1,1,1,9,5,4,0,0,0,0,0,3,3,3,3,3,3,3,3,3,4,3,3,3,3,3,3,3,3,4,3,3,3,4,1,2,3,1,1,1,2601698_x_9,8.0,6.142857,1.0,16.0,5.014265,43.0,21.0,3.000000,3.0,2.0,2.0,14.0,0.0,0.0,0.0,3.571429,3.505098,1.0,11.0,18.0,2.571429,6.0

# 5 Submission

In [6]:
# === 8. Prédiction sur test ===
X_test = test_enriched[X_train.columns]
test_preds_full = model.predict_proba(X_test)[:, 1]

# === 9. Ajouter les prédictions ===
test_enriched['pred'] = test_preds_full

# === 10. Agréger par id_x_rn (même ordre que le test original) ===
submission_df = test_enriched.groupby('id_x_rn')['pred'].mean().reset_index()

# === 11. Renommer pour la soumission ===
submission_df.columns = ['id', 'target'] 

# === 12. Vérification ===
print(f"Shape submission : {submission_df.shape}")  # (654068, 2)
assert 'id' in submission_df.columns and 'target' in submission_df.columns
assert len(submission_df) == 654068

# === 13. Sauvegarde ===
submission_df.to_parquet("submission2.parquet", index=False)
print("SUBMISSION PRÊTE À ÊTRE SOUMISE !")

Shape submission : (654068, 2)
SUBMISSION PRÊTE À ÊTRE SOUMISE !

# 6 Backup

In [ ]:
import joblib 
joblib.dump(model,'fianl_cat_model.pkl')

# TEST ON PRIVATE DATA
VOUS  POUVEZ EXECUTER CETTE SECTION INDEPENDEMMENT DES AUTRES EN IMPORTANT LE MODELE DEJA ENTRAINE .CEPENDANT VOUS DEVEZ PRENDRE LE SOIN DE BIEN PLACER LES CHEMINS D'ACCES DU MODEL  ET DES DATASSETS .

UNE FOIS CELA FAIT, VEILLEZ EXECUTER TOUTES LES SECTIONS CI-DESSOUS

In [20]:
pip install df-squeezer

Collecting df-squeezer
  Downloading df_squeezer-0.0.12.tar.gz (3.1 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from df-squeezer) (2.2.3)
Requirement already satisfied: numpy>=1.18.0 in /usr/local/lib/python3.11/dist-packages (from df-squeezer) (1.26.4)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy>=1.18.0->df-squeezer) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy>=1.18.0->df-squeezer) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy>=1.18.0->df-squeezer) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy>=1.18.0->df-squeezer) (2025.2.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy>=1.18.0->df-squeezer) (2022.2.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy>=1.18.0->df-squeezer) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->df-squeezer) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->df-squeezer) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->df-squeezer) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->df-squeezer) (1.17.0)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.18.0->df-squeezer) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.18.0->df-squeezer) (2022.2.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy>=1.18.0->df-squeezer) (1.4.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy>=1.18.0->df-squeezer) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy>=1.18.0->df-squeezer) (2024.2.0)
Building wheels for collected packages: df-squeezer
  Building wheel for df-squeezer (setup.py) ... done
  Created wheel for df-squeezer: filename=df_squeezer-0.0.12-py3-none-any.whl size=3465 sha256=8934224be739a221f3ccdf1e33e32fa19da9197ba9cb20751067594b3ae168ec
  Stored in directory: /root/.cache/pip/wheels/63/ef/7d/95c3a3c2f0210d1385c2a539837efe342ab657dbff8ed76c3f
Successfully built df-squeezer
Installing collected packages: df-squeezer
Successfully installed df-squeezer-0.0.12
Note: you may need to restart the kernel to use updated packages.

In [30]:
import pandas as pd
import joblib
import gc
from df_squeezer import df_squeezer
from sklearn.metrics import roc_auc_score

In [15]:
model = joblib.load("/kaggle/input/model-path/fianl_cat_model.pkl") # veillez placer le bon chemin d'acces au model

In [16]:
# Assurez vous de bien  placer les chemin d'acces du datasset d'origine et et du datasset priver 
train = pd.read_parquet("/kaggle/input/datassets/train.parquet") # le chemin  à changer 
private_test  = pd.read_parquet("/kaggle/input/datassets/test.parquet") # le chemin  à changer du test en lechim du private data

In [22]:
train=df_squeezer(train, edit=True, report=False)
private_test=df_squeezer(private_test, edit=True, report=False)

## Fonction de transformation des datas du train et du test_privé

In [23]:
def create_global_aggregations_train_test(train, test):
    """
    Crée les agrégations GLOBALES :
    - Fit sur TRAIN uniquement
    - Transform sur TEST (même stats que train)
    """
    # 1. Calcul des agrégations sur TRAIN
    agg_dict = {
        'rn': 'max',
        'pre_loans_credit_limit': ['mean', 'min', 'max', 'std', 'sum'],
        'pre_loans_outstanding': ['sum', 'mean', 'max'],
        'pre_loans_max_overdue_sum': ['max', 'mean', 'sum'],
        'pre_loans_total_overdue': ['sum', 'max', 'mean'],
        'pre_loans_credit_cost_rate': ['mean', 'std', 'min', 'max'],
        'pre_loans_next_pay_summ': ['sum', 'mean', 'max'],
    }
    
    train_agg = train.groupby('id').agg(agg_dict).reset_index()
    train_agg.columns = [
        'id', 'total_loans',
        'avg_credit_limit', 'min_credit_limit', 'max_credit_limit', 'std_credit_limit', 'sum_credit_limit',
        'total_outstanding', 'avg_outstanding', 'max_outstanding',
        'max_overdue_ever', 'avg_max_overdue', 'total_max_overdue',
        'total_overdue_current', 'max_overdue_current', 'avg_overdue_current',
        'avg_credit_cost_rate', 'std_credit_cost_rate', 'min_credit_cost_rate', 'max_credit_cost_rate',
        'total_next_pay_summ', 'avg_next_pay_summ', 'max_next_pay_summ'
    ]
    
    # Remplacer std NaN par 0
    std_cols = [c for c in train_agg.columns if c.startswith('std_')]
    train_agg[std_cols] = train_agg[std_cols].fillna(0)
    
    # 2. Appliquer les mêmes stats au TEST
    test_agg = test[['id']].merge(train_agg, on='id', how='left')
    
    # Pour les clients ABSENTS du train → imputer avec les moyennes du train
    global_means = train_agg.drop(columns='id').mean()
    test_agg = test_agg.fillna(global_means)
    
    return train_agg, test_agg

## Transforamtion du train et private data pour la prediction

In [24]:
train_agg, private_test_agg = create_global_aggregations_train_test(train, private_test)
train_enriched = train.merge(train_agg, on='id', how='left')
private_test_agg_enriched = private_test.merge(private_test_agg, on='id', how='left')
del train, private_test, train_agg, private_test_agg
gc.collect()

24

## PREDICTION

In [28]:
X_train=train_enriched.drop('flag',axis=1)
y_train=train_enriched['flag']

#### Cette partie de code suppose que votre private data a les meme colones que le train ,la colone 'flag' y compris
#### Si tel est le cas ,enlever les commentaires du code ci-dessous.

In [ ]:
X_private_test=private_test_agg_enriched.drop('flag',axis=1)
y_private_test=private_test_agg_enriched['flag']

## Prédiction finale sur les donnés du train

In [32]:
train_preds = model.predict_proba(X_train)[:, 1]
print(f"Train AUC: {roc_auc_score(y_train, train_preds):.6f}")

Train AUC: 0.991343

## Prédiction finale sur les donnés privées

In [ ]:
private_data_preds = model.predict_proba(X_private_test)[:, 1]
print(f"Val AUC: {roc_auc_score(y_private_test, private_data_preds):.6f}")